DROP TABLE IF EXISTS books ;
DROP TABLE IF EXISTS authors ;


CREATE TABLE AUTHORS
(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  FIO VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE  (ID, FIO)
);

CREATE TABLE BOOKS
(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  AUTHOR_ID INTEGER NOT NULL ,
  TITLE VARCHAR(45) NOT NULL,
  IMAGE BLOB,
  TEXT VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE (ID, TITLE),
  FOREIGN KEY ( AUTHOR_ID ) REFERENCES authors ( ID ) ON DELETE CASCADE

);


